### ISSUE TITLE
Good plugin and upload to bukkit pls

### ISSUE THREAD

**Issue by mrrpmrreeoow** [lilmayu/nostalgia-discord#1]
Upload this plugin to [dev.bukkit.org/bukkit-plugins](https://dev.bukkit.org/bukkit-plugins) please : ), its very good plugin

**Comment by lilmayu** [comment]
I won't since this is really just meant for the #saveminecraft Discord + it is really ugly + it has very specific features which were wanted by neil. But I really appreciate it! Thank you very much.
